=== sidleal/ahy/ahy-kernel/ejbModule/resources/ddl/database-create.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="dump">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="table" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="col" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" />
									<xs:attribute name="type" type="xs:string" />
									<xs:attribute name="required" type="xs:boolean" />
									<xs:attribute name="generated" type="xs:boolean" />
									<xs:attribute name="primaryKey" type="xs:boolean" />
									<xs:attribute name="foreignKey" type="xs:string" />
									<xs:attribute name="maxLength" type="xs:string" />
									<xs:attribute name="default" type="xs:boolean" />
									<xs:attribute name="unique" type="xs:boolean" />
								</xs:complexType>
							</xs:element>
							
							<xs:element name="insert" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="col" minOccurs="1" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="key" type="xs:string" />
												<xs:attribute name="value" type="xs:string" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
													
						</xs:sequence>
						<xs:attribute name="name" type="xs:string" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== sidleal/ahy/trunk/ahy-menu/ejbModule/resources/ddl/menu-database-create.xml
<?xml version="1.0" encoding="UTF-8"?>
<dump xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="database-create.xsd">
	<table name="Menu">
	  <col name="id" type="java.lang.Long" required="true" generated="true" primaryKey="true"/>
	  <col name="name" type="java.lang.String" maxLength="100" required="true"/>
	  <col name="path" type="java.lang.String" maxLength="250" required="true"/>
	  <col name="status" type="java.lang.String" maxLength="3" required="true"/>
	  <col name="position" type="java.lang.Integer" required="true" default="0"/>
	  <col name="superMenu_id" type="java.lang.Long" foreignKey="Menu.id"/>
   	  <insert><col key="id" value="1"/><col key="name" value="Menu"/><col key="path" value="/"/><col key="status" value="PUB"/><col key="position" value="0"/></insert>
   	  <insert><col key="id" value="2"/><col key="name" value="Home"/><col key="path" value="/"/><col key="status" value="PUB"/><col key="position" value="0"/><col key="superMenu_id" value="1"/></insert>
   	  <insert><col key="id" value="3"/><col key="name" value="About us"/><col key="path" value="/about.ahy"/><col key="status" value="PUB"/><col key="position" value="0"/><col key="superMenu_id" value="1"/></insert>
   	  <insert><col key="id" value="4"/><col key="name" value="Contact"/><col key="path" value="/contact.ahy"/><col key="status" value="PUB"/><col key="position" value="0"/><col key="superMenu_id" value="1"/></insert>
	</table>
</dump>
